window.TTHK={photos:{'苹果':'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=600&auto=format&q=85','茶':'https://images.unsplash.com/photo-1673537280205-04d2df5aef8a?w=600&auto=format&q=85','狗':'https://images.unsplash.com/photo-1693615774176-a5560f55ac49?w=600&auto=format&q=85','猫':'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&auto=format&q=85','水':'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=600&auto=format&q=85','书':'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&auto=format&q=85','学校':'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&q=85','电脑':'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&q=85','飞机':'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&auto=format&q=85','朋友':'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&auto=format&q=85','牛奶':'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&auto=format&q=85','香蕉':'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&q=85','手机':'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&q=85','花':'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=600&auto=format&q=85','火车':'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=600&auto=format&q=85'},
vi:{'苹果':'Quả táo','茶':'Trà','狗':'Con chó','猫':'Con mèo','水':'Nước','书':'Sách','学校':'Trường học','电脑':'Máy tính','飞机':'Máy bay','朋友':'Bạn bè','牛奶':'Sữa bò','香蕉':'Chuối','手机':'Điện thoại','花':'Hoa','火车':'Tàu hỏa','老师':'Giáo viên','学生':'Học sinh','妈妈':'Mẹ','爸爸':'Bố','你好':'Xin chào','谢谢':'Cảm ơn','再见':'Tạm biệt','学习':'Học tập','喜欢':'Thích','我':'Tôi','你':'Bạn','今天':'Hôm nay','明天':'Ngày mai','中国':'Trung Quốc','吃':'Ăn','喝':'Uống','写':'Viết','看':'Xem'},
base:[['苹果','píng guǒ'],['茶','chá'],['狗','gǒu'],['猫','māo'],['水','shuǐ'],['书','shū'],['学校','xué xiào'],['电脑','diàn nǎo'],['飞机','fēi jī'],['朋友','péng you'],['牛奶','niú nǎi'],['香蕉','xiāng jiāo'],['你好','nǐ hǎo'],['谢谢','xiè xie'],['再见','zài jiàn']],
team:[['Thành Đạt','Leader · Website · Social Media'],['Hồng Diệp','Testing, Evaluation & Communication'],['Yến Vi','Project Coordinator · Support'],['Ngọc Giàu','Content Development'],['Phương Nghi','Presentation & Communication']]};
const D=window.TTHK;D.topic=function(w){let e=(w.en||'').toLowerCase();if(['苹果','茶','水','牛奶','香蕉'].includes(w.h)||/food|rice|eat|drink|fruit|tea|water/.test(e))return'🍎 Ăn uống';if(['狗','猫'].includes(w.h)||/animal|dog|cat/.test(e))return'🐾 Động vật';if(['学校','书','老师','学生'].includes(w.h)||/school|teacher|student|study|book/.test(e))return'🎓 Trường học';if(['朋友','爸爸','妈妈'].includes(w.h)||/family|friend|mother|father/.test(e))return'👥 Gia đình';if(['飞机','火车'].includes(w.h)||/train|plane|car|taxi/.test(e))return'🚉 Đi lại';return'🌿 Sinh hoạt'};
D.speak=function(s){if(!window.speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(s);u.lang='zh-CN';u.rate=.8;speechSynthesis.speak(u)};
D.shuffle=function(a,seed){let b=[...a],n=seed>>>0;for(let i=b.length-1;i>0;i--){n=(n*1664525+1013904223)>>>0;let j=n%(i+1);[b[i],b[j]]=[b[j],b[i]]}return b};
D.card=function(w){const picture=D.photos[w.h]?'<img src="'+D.photos[w.h]+'" alt="'+w.m+'" loading="lazy" onerror="this.outerHTML=\'<div class=placeholder>🈶</div>\'">':'<div class="placeholder">🈶</div>';return'<div class="word box">'+picture+'<h2>'+w.h+'</h2><small>'+w.p+'</small><p>'+w.m+'</p><p class="muted">'+w.topic+' · HSK'+w.l+'</p><div class="row" style="justify-content:center"><button class="btn soft" data-say="'+w.h+'">🔊</button><button class="btn soft" data-write="'+w.h+'">✍</button></div></div>'};
D.bindCards=function(root){root.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>D.speak(b.dataset.say));root.querySelectorAll('[data-write]').forEach(b=>b.onclick=()=>{D.writeIndex=D.words.findIndex(w=>w.h===b.dataset.write);D.charIndex=0;D.isHidden=false;D.page('writing')})};
D.words=[];D.shown=32;D.writeIndex=0;D.charIndex=0;D.isHidden=false;
D.loadWords=async function(){let $=s=>document.querySelector(s);try{let r=await fetch('https://raw.githubusercontent.com/drkameleon/complete-hsk-vocabulary/main/complete.json');if(!r.ok)throw Error();let arr=await r.json();D.words=arr.filter(w=>w.level?.some(z=>z==='old-1'||z==='old-2')).map(w=>({h:w.simplified,p:w.forms?.[0]?.transcriptions?.pinyin||'',en:w.forms?.[0]?.meanings?.[0]||'',l:w.level.includes('old-1')?1:2})).filter(w=>w.h&&w.en).map(w=>({...w,m:D.vi[w.h]||w.en,topic:D.topic(w)}))}catch(e){D.words=D.base.map(x=>({h:x[0],p:x[1],en:x[0],m:D.vi[x[0]],l:1,topic:D.topic({h:x[0],en:x[0]})}));$('#wordStatus').textContent='Nguồn HSK chưa tải được, đang hiện danh sách dự phòng.'}D.words.sort((a,b)=>Number(!!D.photos[b.h])-Number(!!D.photos[a.h]));$('#writeSelect').innerHTML=D.words.map((w,i)=>'<option value="'+i+'">'+w.h+' — '+w.m+'</option>').join('');$('#topic').innerHTML='<option value="all">Tất cả chủ đề</option>'+[...new Set(D.words.map(w=>w.topic))].map(x=>'<option>'+x+'</option>').join('');if(!$('#wordStatus').textContent.includes('dự phòng'))$('#wordStatus').textContent=D.words.length+' từ vựng · '+D.words.filter(w=>D.photos[w.h]).length+' từ có ảnh thực tế được gắn riêng. Không tìm ảnh ngẫu nhiên.';D.vocab();D.lookup()};
D.vocab=function(){let $=s=>document.querySelector(s),lv=$('#level').value,t=$('#topic').value,q=$('#vocabQuery').value.toLowerCase();let arr=D.words.filter(w=>(lv==='all'||w.l==lv)&&(t==='all'||w.topic===t)&&(!$('#onlyPhotos').checked||!!D.photos[w.h])&&[w.h,w.p,w.m,w.en].some(x=>x.toLowerCase().includes(q)));$('#wordGrid').innerHTML=arr.slice(0,D.shown).map(D.card).join('');D.bindCards($('#wordGrid'));$('#loadMore').hidden=D.shown>=arr.length};
D.lookupType='words';D.lookup=function(){let $=s=>document.querySelector(s),q=$('#query').value.toLowerCase(),a=D.words.filter(w=>!q||[w.h,w.p,w.m,w.en].some(x=>x.toLowerCase().includes(q))).slice(0,12),r=$('#result');if(D.lookupType==='words')r.innerHTML=a.map(D.card).join('');else if(D.lookupType==='hanzi')r.innerHTML=a.map(w=>'<div class="box"><h2>'+w.h+'</h2><p>'+w.p+' — '+w.m+'</p><button class="btn soft" data-write="'+w.h+'">✍ Viết</button></div>').join('');else if(D.lookupType==='examples')r.innerHTML=[['你好','你好！'],['苹果','我喜欢苹果。'],['茶','我喝茶。'],['学习','我学习中文。'],['学校','我去学校。']].filter(x=>!q||x.join('').includes(q)).map(x=>'<div class="box"><h2>'+x[1]+'</h2><p>'+x[0]+'</p></div>').join('');else if(D.lookupType==='grammar')r.innerHTML=['是 — 我是学生。','有 — 我有书。','不 — 我不喝茶。'].map(x=>'<div class="box">'+x+'</div>').join('');else r.innerHTML=['喝水 — uống nước','吃饭 — ăn cơm','看书 — đọc sách','学习中文 — học tiếng Trung'].filter(x=>!q||x.includes(q)).map(x=>'<div class="box">'+x+'</div>').join('');D.bindCards(r);if(!r.innerHTML)r.textContent='Chưa có dữ liệu phù hợp.'};
